name: docsgpt-oss
services:
  frontend:
    build: ../frontend
    env_file:
      - .env
    environment:
      - VITE_API_HOST=http://localhost:7091
      - VITE_API_STREAMING=${VITE_API_STREAMING}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - ENV=production
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    user: root
    build: ../application
    command: >
      gunicorn -w 1 --timeout 120 --bind 0.0.0.0:7091 application.app:app
    env_file:
      - .env
    runtime: nvidia
    environment:
      - API_KEY=${API_KEY}
      - EMBEDDINGS_KEY=
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_NAME=${LLM_NAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - CACHE_REDIS_URL=redis://redis:6379/2
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - INTERNAL_KEY=${INTERNAL_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "7091:7091"
    volumes:
      - D:/Github/KLTN/DocsGPT/application/indexes:/app/indexes
      - D:/Github/KLTN/DocsGPT/application/inputs:/app/inputs
      - D:/Github/KLTN/DocsGPT/application/vectors:/app/vectors
      - D:/Github/KLTN/DocsGPT/application/inputs/local:/app/application/inputs/local
    depends_on:
      - redis
      - mongo
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  worker:
    user: root
    build: ../application
    command: celery -A application.app.celery worker -l INFO
    env_file:
      - .env
    environment:
      - API_KEY=${API_KEY}
      - EMBEDDINGS_KEY=
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_NAME=${LLM_NAME}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:7091
      - CACHE_REDIS_URL=redis://redis:6379/2
      - INTERNAL_KEY=${INTERNAL_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
      - USE_GPU=true
    volumes:
      - D:/Github/KLTN/DocsGPT/application/indexes:/app/indexes
      - D:/Github/KLTN/DocsGPT/application/inputs:/app/inputs
      - D:/Github/KLTN/DocsGPT/application/vectors:/app/vectors
      - D:/Github/KLTN/DocsGPT/application/inputs/local:/app/application/inputs/local
    depends_on:
      - redis
      - mongo
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  beat:
    build: ../application
    command: celery -A application.app.celery beat -l INFO
    env_file:
      - .env
    depends_on:
      - redis
      - mongo

volumes:
  mongodb_data_container:
